# Generated by Django 4.0.4 on 2022-05-04 21:41

from django.db import migrations
import djongo.models.fields
import studentApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subscription',
            field=djongo.models.fields.EmbeddedField(default='', model_container=studentApp.models.Subscription),
        ),
    ]
